### ISSUE TITLE
Need to mount/unmount after alt-tabbing to regain functionaility

### ISSUE THREAD

**Issue by TheWhiteWolves** [Friendly0Fire/GW2Addons#13] opened 2017-10-15 11:19 UTC
Don't know if this is just me or not as I haven't had a chance to do extensive testing on the issue, but what I have found is that if you Alt-Tab out of the game and back in, or move off the game and back (i.e. if you have multiple monitors and you click on something else then back on the game) the addon will stop issuing the commands to mount when used, you then have to mount as you would normally without the addon and dismount in order to get the addon to function again.

My suspicion is that the addon is sending the commands to a different window or not to the gw2 window after the focus is lost on the game and it is only when the mount event is triggered that it regains it.

I am running v0.2 from the releases page.

**Comment by mseiei** [comment] 2017-10-19 23:44
experiencing the same issue but the only mount affected is Griffon, the other 4 mounts works as intended
Steps to reproduce: 
Alt+tab, return to GW2, try to mount Griffon

**Comment by Friendly0Fire** [comment] 2017-10-23 17:55
Are you both running the game in fullscreen or windowed/windowed fullscreen? I can see why it'd break in the former case, but will need to look around.

**Comment by TheWhiteWolves** [comment] 2017-10-24 08:25
I'm running windowed fullscreen

**Comment by Zefrost** [comment] 2017-10-24 16:39
I have this issue as well. Windowed mode.

**Comment by zpcp** [comment] 2017-10-30 04:35
Cannot reproduce - Alt-Tab-ing away from the game doesn't break functionality. 

Windowed Fullscreen @ 1440p, 
ArcDPS + Build Templates + Mounts (renamed to d3d9_chainload.dll)
Windows 10 Pro, build 1709, no frame rate workaround applied (the compatibility thingie)

Using these keys for mounts:

Raptor: [
Springer: ]
Skimmer: ;
Jackal: '
Griffon: \

UI wheel keybind: G

INI files contents:

[General]
reset_cursor_on_locked_keybind = true
lock_camera_when_overlayed = true
show_fifth_mount = true

[Keybinds]
mount_0 = 219
mount_1 = 221
mount_2 = 186
mount_3 = 222
mount_4 = 220
mount_wheel = 71

[Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Mounts Options Menu]
Pos=60,60
Size=387,324
Collapsed=0

**Comment by Friendly0Fire** [comment] 2018-06-24 01:16
Fix for #12 should resolve this as well. Closing for now.

**Closed by Friendly0Fire** 2018-06-24 01:16 UTC
Labels: bug
