### ISSUE TITLE
Menu doesn't highlight properly with 6 mounts

### ISSUE THREAD

**Issue by DJ-Zephyr** [Friendly0Fire/GW2Addons#45] opened 2018-09-11 14:59 UTC
**Describe the bug**
When I have 5 mounts bound, the menu highlights properly.  When I have all 6 bound, it highlights the wrong mount upon mouseover.  Upon releasing the button, it seems to work properly, as the mount the mouse is over gets selected.

**To Reproduce**
1. Hold overlay bind.
2. Hover over mount desired.
3. It highlights the next mount clockwise from it.

**Expected behavior**
I expect the mount the mouse is over to be highlighted.

**Screenshots**
Album for ya: https://imgur.com/a/GtsZ4RC

**System configuration (please fill in):**
Windows 10
AMD R9-380 4G
No chainloading, I do use TacO from time to time.

**Additional context**
Also happens with uncentered binding.

**Comment by Friendly0Fire** [comment] 2018-09-26 16:03
Duplicate of #28

**Closed by Friendly0Fire** 2018-09-26 16:03 UTC
